import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Box, Heading } from '@chakra-ui/react';
import styles from '../styles/Home.module.css';
import Game from './components/Game';
import LottieCoinFlip from './components/LottieCoinFlip';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CoinFlip 🤑</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
      <Heading as='h2' size='2xl'>
      Welcome to CoinFlip.Next
      </Heading>

      <Heading as='h4' size='md'>
        something nice here!
      </Heading>
      
      <p><ConnectButton /></p>
        <Box width={640}>
          <LottieCoinFlip />
          <Game />
        </Box>
        
      </main>

      <footer className={styles.footer}>
        <a href="https://github.com/Eklvya13" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by Hari Acharya
        </a>
      </footer>
    </div>
  );
};

export default Home;